### ISSUE TITLE
julec: compiler doesn't seem to work very well

### ISSUE THREAD

**Issue by lareii** [the-xlang/x#4]
I tried to transpile the code in the [document](https://jule.dev/pages/docs.html?page=cpp-interoperability) but doesn't seem to work. After transpiled the code, `dist` directory was created but the code wasn't converted to the `.cpp` file.

**Comment by mertcandav** [comment]
Hi, please describe what did you do.
Share your Jule code and followed steps.

**Comment by lareii** [comment]
**I transpiled the code below but JuleC didn't create the `jule.cpp` file. Also, I didn't get any error.**

sum_integers.hpp:
```
i64_julet sum_integers(const slice<int_julet> &_Slice) {
    i64_julet total{0};
    for (const int_julet &x: _Slice) {
        total += x;
    }
    return total;
}
```

main.jule:
```
use cpp "sum_integers.hpp"

cpp fn sum_integers(slice: []int) i64

fn main() {
    let slice = []int{90, 34, 63, -34, 3246, -95, 734, 0, 3}
    let total = cpp.sum_integers(slice)
    outln(total)
}
```

**Comment by mertcandav** [comment]
What is your operating system?

**Comment by lareii** [comment]
I'm using Windows.

**Comment by mertcandav** [comment]
Please confirm this issue is fixed.

**Comment by lareii** [comment]
It now works correctly. Thanks.

**Comment by mertcandav** [comment]
The problem reason is the `use` declaration of C++ interoperability.
JuleC changes working directory to package directory for checking used header file path is valid or not, sets working directory to compiler directory after checking and compiler lose your real working directory, your working directory changes to the compiler directory.

You never got an error because compilation is really successful.
You didn't see your generated C++ codes because your generated C++ codes and `dist` directory created at directory of compiler executable file.

Thanks for your contribution.
